version: '3.9'
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports: ['27017:27017']
    volumes: ['mongo_data:/data/db']
  api:
    build: ./server
    ports: ['4000:4000']
    environment:
      - MONGO_URI=mongodb://mongo:27017/hms
      - JWT_SECRET=supersecret_change_me
      - COOKIE_SECURE=false
      - CORS_ORIGIN=http://localhost:5173
    depends_on: ['mongo']
  web:
    build: ./web
    ports: ['5173:5173']
    environment:
      - VITE_API_BASE=http://localhost:4000/api
    depends_on: ['api']
volumes:
  mongo_data:
